import AuthContext from './context/AuthContext'
import CountContext from './context/CountContext'
import ThemeContext from './context/ThemeContext'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CountContext>
        <ThemeContext>
          <AuthContext>
            {children}
          </AuthContext>
        </ThemeContext>
        </CountContext>
      </body>
    </html>
  )
}
